/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package shopping.cart

import io.kotest.core.spec.style.StringSpec

class ShoppingCartShould:StringSpec( {
    "I want to see my shopping cart" {
        //val shoppingCart = ShoppingCart()
    }
})
